language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - bvicente@fi.uba.ar
      - morgan_pirata2003@yahoo.com.ar
      - joaquin_andresen@icloud.com
      - fernando.fabbiano@gmail.com
    on_success: never
    on_failure: always
